<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <RootNamespace>RynthCore.Loader</RootNamespace>
    <AssemblyName>RynthCore.Loader</AssemblyName>

    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <StackTraceSupport>false</StackTraceSupport>
    <TrimMode>link</TrimMode>

    <Platforms>x86</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <StackTraceSupport>true</StackTraceSupport>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

</Project>
