<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RynthCore.HookManifest</RootNamespace>
    <AssemblyName>RynthCore.HookManifest</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
